# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesresourceinstance',
            name='kubectl_state',
            field=models.CharField(blank=True, choices=[(b'created', b'CREATED'), (b'updated', b'UPDATED'), (b'deleted', b'DELETED')], help_text=b'Most recent kubectl action completed by synchronizer', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetesresourceinstance',
            name='resource_definition',
            field=models.CharField(blank=True, help_text=b'yaml containing kubernetes resources', max_length=65535, null=True),
        ),
    ]
